/**
 * Biografía recuperada de la web anterior (pablocebrian.es), usada como
 * contenido inicial hasta que se guarde algo desde /admin/bio.
 */
export const DEFAULT_BIO_HTML = `
<p>Soy un músico, compositor y productor canario afincado en Madrid desde 2001. Mi relación con la música comenzó desde muy joven, pero mi primer trabajo profesional llegó a los 19 años, cuando el productor canario <strong>Kike Perdomo</strong> me dio la oportunidad de colaborar como guitarrista y autor en uno de los discos que estaba produciendo.</p>
<p>Aquella experiencia marcó el inicio de un camino que continuó en los estudios Multitrack de <strong>Paco Chinea</strong>, donde desempeñé múltiples funciones: técnico de sonido, guitarrista, programador y productor. Fue una etapa apasionante, coincidiendo con la revolución de la informática musical, que me permitió desarrollar una visión amplia y profunda del proceso creativo y de producción.</p>
<p>Poco después me trasladé a Madrid junto a <strong>Iván Mur</strong> para perseguir nuestro sueño con <strong>Fábula</strong>. Gracias al apoyo y la confianza del mánager <strong>Vicente Mañó</strong>, conseguimos fichar por <strong>Warner Music</strong>. Durante esa etapa publicamos dos álbumes y ofrecimos más de 80 conciertos, entre ellos una gira por toda España como teloneros de la mítica banda estadounidense <strong>R.E.M.</strong></p>
<p>Tras la disolución de Fábula en 2008, decidí dar un paso atrás en los escenarios para centrarme en dos de mis grandes pasiones: la composición y la producción musical. Desde entonces, he tenido la oportunidad de trabajar con algunos de los artistas más relevantes del panorama nacional e internacional, desarrollando una carrera marcada por la búsqueda constante de la belleza y la autenticidad.</p>
<p>He sido nominado en cinco ocasiones a los <strong>Latin Grammy</strong> y he participado en proyectos reconocidos con <strong>Premios Ondas</strong>, además de recibir el premio a la Mejor Canción en los <strong>Premios 40 Principales</strong>, el <strong>Premio Apolo</strong> a la Mejor Sintonía de Televisión y el <strong>Premio Click &amp; Roll</strong> al Mejor Productor, entre otros reconocimientos. Mis producciones y composiciones han alcanzado múltiples discos de platino, consolidando una trayectoria que combina el éxito comercial con el compromiso creativo.</p>
<p>A lo largo de los años he compaginado mi labor como productor y compositor con la dirección artística de grandes eventos musicales. Tuve el honor de ser director artístico de la visita del <strong>Papa León XIV</strong> a España, coordinando la producción del evento junto a <strong>Javier Llano</strong> y participando en la composición y produciendo el himno oficial, <strong>«Alza la Mirada»</strong>, concebido como el eje musical y emocional de una celebración histórica.</p>
<p>Asimismo, tuve la oportunidad de dirigir artísticamente, junto a <strong>Carlos Narea</strong>, la gala de los Latin Grammy dedicada a la celebración de Andalucía. También he dirigido el concierto del 30.º aniversario de <strong>Cadena 100</strong> en el Estadio Wanda Metropolitano, así como numerosas ediciones de <strong>Por Ellas</strong>, uno de los eventos benéficos más importantes del panorama musical en España. También dirigí artísticamente la tercera edición de Los Premios de la Academia de la Música española en el año 2026.</p>
<p>En 2022 fundé <strong>Halley Music</strong>, un hub artístico de referencia en Madrid concebido como un espacio para la creación, la colaboración y el encuentro entre artistas. Con nueve estudios de grabación y un enfoque profundamente humano, Halley Music se ha convertido en un punto de encuentro para compositores, productores e intérpretes que buscan desarrollar su trabajo en un entorno cercano, inspirador y al servicio de la música.</p>
<p>Más de dos décadas después de mi llegada a Madrid, sigo afrontando cada proyecto con la misma ilusión que aquel joven de 19 años que entró por primera vez en un estudio de grabación convencido de que la música sería el viaje de su vida.</p>
`.trim();
