import { Album } from "./types";

/**
 * Discografía completa recuperada de la web anterior (pablocebrian.es,
 * Wix) mientras el cliente confirma fechas y sellos. Las portadas son las
 * originales del sitio. Una vez configurado Supabase, estos datos dejan de
 * usarse: se sustituyen por lo que el propio Pablo cargue desde
 * /admin/discos.
 */
function album(partial: {
  id: string;
  slug: string;
  title: string;
  artist_names: string[];
  role: string;
  cover_url: string;
  featured: boolean;
  sort_order: number;
  spotify_url?: string;
  apple_music_url?: string;
}): Album {
  return {
    release_year: null,
    label: null,
    spotify_url: null,
    apple_music_url: null,
    youtube_url: null,
    show_spotify: true,
    show_apple_music: true,
    published: true,
    ...partial,
  };
}

export const PLACEHOLDER_ALBUMS: Album[
  ] = [
  album({
    id: "disco-1",
    slug: "manuel-carrasco-la-cruz-del-mapa",
    title: "La Cruz Del Mapa",
    artist_names: ["Manuel Carrasco"],
    role: "Composer / Lyricist / Producer / Arranger / Guitar / Programmer / Piano / Vocals",
    cover_url: "/discografia/manuel-carrasco-la-cruz-del-mapa.jpg",
    featured: true,
    sort_order: 1,
  }),
  album({
    id: "disco-2",
    slug: "siloe-santa-trinidad",
    title: "Santa Trinidad",
    artist_names: ["Siloé"],
    role: "Composer / Lyricist / Arranger / Producer",
    cover_url: "/discografia/siloe-santa-trinidad.jpg",
    featured: true,
    sort_order: 2,
  }),
  album({
    id: "disco-3",
    slug: "pedro-guerra-parceiros-vol-2",
    title: "Parceiros, Vol. 2",
    artist_names: ["Pedro Guerra"],
    role: "Producer / Arranger / Guitar / Bass / Programmer",
    cover_url: "/discografia/pedro-guerra-parceiros-vol-2.jpg",
    featured: true,
    sort_order: 3,
  }),
  album({
    id: "disco-4",
    slug: "luz-casal-me-voy-a-permitir",
    title: "Me Voy A Permitir",
    artist_names: ["Luz Casal"],
    role: "Composer",
    cover_url: "/discografia/luz-casal-me-voy-a-permitir.jpg",
    featured: true,
    sort_order: 4,
  }),
  album({
    id: "disco-5",
    slug: "residente-rap-bruto",
    title: "Rap Bruto",
    artist_names: ["Residente", "Nach"],
    role: "Composer / Lyricist / Producer / Arranger / Programmer",
    cover_url: "/discografia/residente-rap-bruto.jpg",
    featured: true,
    sort_order: 5,
  }),
  album({
    id: "disco-6",
    slug: "carlos-rivera-para-ti",
    title: "Para Ti",
    artist_names: ["Carlos Rivera"],
    role: "Lyricist / Composer / Producer / Bass",
    cover_url: "/discografia/carlos-rivera-para-ti.jpg",
    featured: true,
    sort_order: 6,
  }),
  album({
    id: "disco-7",
    slug: "vivafe-alzo-la-mirada",
    title: "Alzo la Mirada",
    artist_names: ["VIVAFE", "Gran Coro de Voces Católicas"],
    role: "Composer / Lyricist / Producer / Arranger / Guitar / Bass / Programmer",
    cover_url: "/discografia/vivafe-alzo-la-mirada.jpg",
    featured: true,
    sort_order: 7,
  }),
  album({
    id: "disco-8",
    slug: "manuel-carrasco-bailar-el-viento",
    title: "Bailar El Viento",
    artist_names: ["Manuel Carrasco"],
    role: "Producer / Arranger / Bass / Guitar / Programmer",
    cover_url: "/discografia/manuel-carrasco-bailar-el-viento.jpg",
    featured: true,
    sort_order: 8,
  }),
  album({
    id: "disco-9",
    slug: "conchita-la-orilla",
    title: "La Orilla",
    artist_names: ["Conchita"],
    role: "Producer / Programmer / Guitar / Bass / Piano",
    cover_url: "/discografia/conchita-la-orilla.jpg",
    featured: true,
    sort_order: 9,
  }),
  album({
    id: "disco-10",
    slug: "aitana-spoiler",
    title: "Spoiler",
    artist_names: ["Aitana"],
    role: "Producer",
    cover_url: "/discografia/aitana-spoiler.jpg",
    featured: true,
    sort_order: 10,
  }),
  album({
    id: "disco-11",
    slug: "antonito-molina-dejemos-huellas-bonitas",
    title: "Dejemos Huellas Bonitas",
    artist_names: ["Antoñito Molina"],
    role: "Producer",
    cover_url: "/discografia/antonito-molina-dejemos-huellas-bonitas.jpg",
    featured: true,
    sort_order: 11,
  }),
  album({
    id: "disco-12",
    slug: "david-bisbal-en-tus-planes",
    title: "En Tus Planes",
    artist_names: ["David Bisbal"],
    role: "Co-Producer",
    cover_url: "/discografia/david-bisbal-en-tus-planes.jpg",
    featured: true,
    sort_order: 12,
  }),
  album({
    id: "disco-13",
    slug: "tuyo-tu-el-unico-rey-una-voz",
    title: "(Tú) El Único Rey - Una Voz",
    artist_names: ["Tuyo", "Hakuna Group Music", "Aisha Ruah"],
    role: "Producer / Piano / Programmer / Bass / Guitar / Keyboard",
    cover_url: "/discografia/tuyo-tu-el-unico-rey-una-voz.jpg",
    featured: true,
    sort_order: 13,
  }),
  album({
    id: "disco-14",
    slug: "ketama-de-aki-a-ketama",
    title: "De Akí A Ketama",
    artist_names: ["Ketama"],
    role: "Producer / Programmer",
    cover_url: "/discografia/ketama-de-aki-a-ketama.jpg",
    featured: true,
    sort_order: 14,
  }),
  album({
    id: "disco-15",
    slug: "gonzalo-hermida-bandera-libertad",
    title: "Bandera Libertad",
    artist_names: ["Gonzalo Hermida", "Andrés Koi"],
    role: "Composer / Lyricist / Producer",
    cover_url: "/discografia/gonzalo-hermida-bandera-libertad.jpg",
    featured: true,
    sort_order: 15,
  }),
  album({
    id: "disco-16",
    slug: "resistire-2020-resistire",
    title: "Resistiré",
    artist_names: ["Resistiré 2020"],
    role: "Producer / Guitar",
    cover_url: "/discografia/resistire-2020-resistire.jpg",
    featured: true,
    sort_order: 16,
  }),
  album({
    id: "disco-17",
    slug: "viva-suecia-alegria-de-vivir",
    title: "Alegría De Vivir",
    artist_names: ["Viva Suecia"],
    role: "Producer / Guitar / Vocals",
    cover_url: "/discografia/viva-suecia-alegria-de-vivir.jpg",
    featured: true,
    sort_order: 17,
  }),
  album({
    id: "disco-18",
    slug: "david-bisbal-todo-es-posible-en-navidad",
    title: "Todo Es Posible En Navidad",
    artist_names: ["David Bisbal"],
    role: "Composer / Lyricist",
    cover_url: "/discografia/david-bisbal-todo-es-posible-en-navidad.jpg",
    featured: true,
    sort_order: 18,
  }),
  album({
    id: "disco-19",
    slug: "luz-casal-que-has-hecho-conmigo",
    title: "¿Qué Has Hecho Conmigo?",
    artist_names: ["Luz Casal"],
    role: "Composer / Guitar",
    cover_url: "/discografia/luz-casal-que-has-hecho-conmigo.jpg",
    featured: true,
    sort_order: 19,
  }),
  album({
    id: "disco-20",
    slug: "pedro-guerra-parceiros-vol-3",
    title: "Parceiros, Vol. 3",
    artist_names: ["Pedro Guerra"],
    role: "Producer / Guitar / Bass / Programmer",
    cover_url: "/discografia/pedro-guerra-parceiros-vol-3.jpg",
    featured: true,
    sort_order: 20,
  }),
  album({
    id: "disco-21",
    slug: "taburete-matadero-5",
    title: "Matadero 5",
    artist_names: ["Taburete"],
    role: "Producer / Arranger / Guitar / Bass / Programmer",
    cover_url: "/discografia/taburete-matadero-5.jpg",
    featured: true,
    sort_order: 21,
  }),
  album({
    id: "disco-22",
    slug: "bunbury-cuentas-pendientes",
    title: "Cuentas Pendientes",
    artist_names: ["Bunbury"],
    role: "Arranger",
    cover_url: "/discografia/bunbury-cuentas-pendientes.jpg",
    featured: true,
    sort_order: 22,
  }),
  album({
    id: "disco-23",
    slug: "sole-gimenez-ser-humano",
    title: "Ser Humano",
    artist_names: ["Sole Giménez"],
    role: "Composer / Producer / Lyricist / Bass / Guitar / Keyboard",
    cover_url: "/discografia/sole-gimenez-ser-humano.jpg",
    featured: true,
    sort_order: 23,
  }),
  album({
    id: "disco-24",
    slug: "beret-si-te-vuelvo-a-llamar",
    title: "Si Te Vuelvo A Llamar",
    artist_names: ["Beret"],
    role: "Producer / Guitar / Keyboard / Programmer",
    cover_url: "/discografia/beret-si-te-vuelvo-a-llamar.jpg",
    featured: true,
    sort_order: 24,
  }),
  album({
    id: "disco-25",
    slug: "hakuna-group-music-tu",
    title: "Tú",
    artist_names: ["Hakuna Group Music", "Aisha Ruah", "Clara H.", "Ecos Música"],
    role: "Composer / Producer / Piano / Programmer / Guitar / Keyboard / Bass",
    cover_url: "/discografia/hakuna-group-music-tu.jpg",
    featured: true,
    sort_order: 25,
  }),
  album({
    id: "disco-26",
    slug: "andres-koi-sol-de-invierno",
    title: "Sol De Invierno",
    artist_names: ["Andrés Koi", "Taburete"],
    role: "Producer / Programmer / Guitar / Bass",
    cover_url: "/discografia/andres-koi-sol-de-invierno.jpg",
    featured: false,
    sort_order: 26,
  }),
  album({
    id: "disco-27",
    slug: "antonio-jose-luz",
    title: "Luz",
    artist_names: ["Antonio José"],
    role: "Producer / Composer / Lyricist",
    cover_url: "/discografia/antonio-jose-luz.jpg",
    featured: false,
    sort_order: 27,
  }),
  album({
    id: "disco-28",
    slug: "hermanos-martinez-contacto-de-emergencia",
    title: "Contacto De Emergencia",
    artist_names: ["Hermanos Martínez", "Mau y Ricky"],
    role: "Producer",
    cover_url: "/discografia/hermanos-martinez-contacto-de-emergencia.jpg",
    featured: false,
    sort_order: 28,
  }),
  album({
    id: "disco-29",
    slug: "marquitos-bucle",
    title: "Bucle",
    artist_names: ["Marquitos"],
    role: "Producer / Guitar / Piano",
    cover_url: "/discografia/marquitos-bucle.jpg",
    featured: false,
    sort_order: 29,
  }),
  
  // Discos incorporados en una segunda pasada de scraping de pablocebrian.es
  // (el sitio Wix creció desde la primera carga): el campo "role" solo está
  // confirmado cuando se pudo leer el overlay de créditos en la web; el
  // resto usa "Producer" como valor por defecto y conviene revisarlo desde
  // /admin/discos.
  album({
    id: "disco-30",
    slug: "sergio-dalma-dalma",
    title: "Dalma",
    artist_names: ["Sergio Dalma"],
    role: "Composer / Producer",
    cover_url: "/discografia/sergio-dalma-dalma.jpg",
    spotify_url: "https://open.spotify.com/album/6sCd4jB6jpDJxCkFpozDlY",
    apple_music_url: "https://music.apple.com/es/album/dalma/1047545211",
    featured: false,
    sort_order: 30,
  }),
  album({
    id: "disco-31",
    slug: "morat-balas-perdidas",
    title: "Balas Perdidas",
    artist_names: ["Morat"],
    role: "Producer",
    cover_url: "/discografia/morat-balas-perdidas.jpg",
    spotify_url: "https://open.spotify.com/album/43mAHKPa4iB2er88lxD9Q8",
    apple_music_url: "https://music.apple.com/us/album/balas-perdidas/1438883863",
    featured: false,
    sort_order: 31,
  }),
  album({
    id: "disco-32",
    slug: "pastora-soler-la-calma",
    title: "La Calma",
    artist_names: ["Pastora Soler"],
    role: "Producer",
    cover_url: "/discografia/pastora-soler-la-calma.jpg",
    spotify_url: "https://open.spotify.com/album/5mgibqvJsmJyG5XoGZnjgG",
    apple_music_url: "https://music.apple.com/us/album/la-calma/1265174898",
    featured: false,
    sort_order: 32,
  }),
  album({
    id: "disco-33",
    slug: "santiago-cruz-a-quien-corresponda",
    title: "A Quien Corresponda",
    artist_names: ["Santiago Cruz"],
    role: "Producer",
    cover_url: "/discografia/santiago-cruz-a-quien-corresponda.jpg",
    spotify_url: "https://open.spotify.com/album/4FbRi2JEQn1PLlP4Op9fmS",
    apple_music_url: "https://music.apple.com/co/album/santiago-cruz-a-quien-corresponda-cartas-abiertas-y/740198093",
    featured: false,
    sort_order: 33,
  }),
  album({
    id: "disco-34",
    slug: "antonito-molina-abel-pintos-me-subo-por-las-paredes",
    title: "Me Subo Por Las Paredes",
    artist_names: ["Antoñito Molina", "Abel Pintos"],
    role: "Producer",
    cover_url: "/discografia/antonito-molina-abel-pintos-me-subo-por-las-paredes.jpg",
    spotify_url: "https://open.spotify.com/intl-es/track/7nRJo5qJM4jCKFpqJ06xpV",
    apple_music_url: "https://music.apple.com/es/song/me-subo-por-las-paredes/1818433980",
    featured: false,
    sort_order: 34,
  }),
  album({
    id: "disco-35",
    slug: "marquitos-mis-idolos-estan-en-mi-casa",
    title: "Mis Ídolos Están En Mi Casa",
    artist_names: ["Marquitos"],
    role: "Producer",
    cover_url: "/discografia/marquitos-mis-idolos-estan-en-mi-casa.jpg",
    spotify_url: "https://open.spotify.com/track/6RIBmb2ULjexyrf9iAWXTU",
    apple_music_url: "https://music.apple.com/hu/song/mis-%C3%ADdolos-est%C3%A1n-en-mi-casa/1794594984",
    featured: false,
    sort_order: 35,
  }),
  album({
    id: "disco-36",
    slug: "conchita-bola-de-nieve",
    title: "Bola De Nieve",
    artist_names: ["Conchita"],
    role: "Composer / Producer / Programmer / Choir / Guitar / Vocals",
    cover_url: "/discografia/conchita-bola-de-nieve.jpg",
    spotify_url: "https://open.spotify.com/album/7HibTT3s5wcxnRHJ2mAfsU",
    apple_music_url: "https://music.apple.com/es/album/la-bola-de-nieve/1675926924",
    featured: false,
    sort_order: 36,
  }),
  album({
    id: "disco-37",
    slug: "nach-keny-garcia-in-memoriam",
    title: "In Memoriam",
    artist_names: ["Nach", "Kany García"],
    role: "Producer",
    cover_url: "/discografia/nach-keny-garcia-in-memoriam.jpg",
    spotify_url: "https://open.spotify.com/track/7cevPdNaGJc3pUwmQLq5YP",
    apple_music_url: "https://music.apple.com/us/song/in-memoriam/1600084315",
    featured: false,
    sort_order: 37,
  }),
  album({
    id: "disco-38",
    slug: "india-martinez-marc-anthony-convenceme",
    title: "Convénceme",
    artist_names: ["India Martínez", "Marc Anthony"],
    role: "Producer",
    cover_url: "/discografia/india-martinez-marc-anthony-convenceme.jpg",
    spotify_url: "https://open.spotify.com/track/12oFSoib1tf0r2rd1Fgsfe",
    apple_music_url: "https://music.apple.com/us/album/conv%C3%A9nceme/1531875600?i=1531875604",
    featured: false,
    sort_order: 38,
  }),
  album({
    id: "disco-39",
    slug: "luciano-pereyra-22-de-marzo",
    title: "22 De Marzo",
    artist_names: ["Luciano Pereyra"],
    role: "Composer / Lyricist / Producer / Arranger / Bass / Guitar / Programmer",
    cover_url: "/discografia/luciano-pereyra-22-de-marzo.jpg",
    spotify_url: "https://open.spotify.com/track/2apG9brHB5vHSKIbLMrbUP",
    apple_music_url: "https://music.apple.com/us/album/22-de-marzo-single/1825393084",
    featured: false,
    sort_order: 39,
  }),
  album({
    id: "disco-40",
    slug: "hermanos-martinez-para-que-me-escribes",
    title: "Para Qué Me Escribes",
    artist_names: ["Hermanos Martínez"],
    role: "Producer",
    cover_url: "/discografia/hermanos-martinez-para-que-me-escribes.jpg",
    spotify_url: "https://open.spotify.com/track/6nsxFpePTfrSIG4cVvzfCL",
    apple_music_url: "https://music.apple.com/us/album/para-qu%C3%A9-me-escribes-single/1765507172",
    featured: false,
    sort_order: 40,
  }),
  album({
    id: "disco-41",
    slug: "carlos-rivera-leyendas",
    title: "Leyendas",
    artist_names: ["Carlos Rivera"],
    role: "Producer",
    cover_url: "/discografia/carlos-rivera-leyendas.jpg",
    spotify_url: "https://open.spotify.com/album/6J6kRBEpL4bAkfL8DXXWiU",
    apple_music_url: "https://music.apple.com/us/album/leyendas/1567319532",
    featured: false,
    sort_order: 41,
  }),
  album({
    id: "disco-42",
    slug: "nikone-on-nikone",
    title: "Onirikone",
    artist_names: ["Nikone"],
    role: "Producer",
    cover_url: "/discografia/nikone-on-nikone.jpg",
    spotify_url: "https://open.spotify.com/album/57Hqmz2tIvke4mWmJaXU80",
    apple_music_url: "https://music.apple.com/es/album/onirikone/1204840546",
    featured: false,
    sort_order: 42,
  }),
  album({
    id: "disco-43",
    slug: "nach-almanauta",
    title: "Almanauta",
    artist_names: ["Nach"],
    role: "Producer",
    cover_url: "/discografia/nach-almanauta.jpg",
    spotify_url: "https://open.spotify.com/album/78bbjiERGysWG8XhqEAnbV",
    apple_music_url: "https://music.apple.com/us/album/almanauta/1438776342",
    featured: false,
    sort_order: 43,
  }),
  album({
    id: "disco-44",
    slug: "dani-fernandez-en-llamas-ep",
    title: "En Llamas (EP)",
    artist_names: ["Dani Fernández"],
    role: "Producer",
    cover_url: "/discografia/dani-fernandez-en-llamas-ep.jpg",
    spotify_url: "https://open.spotify.com/album/5Q7igsQWEBxlJMrNNM3Y3L",
    apple_music_url: "https://music.apple.com/es/album/en-llamas-ep/1441994006",
    featured: false,
    sort_order: 44,
  }),
  album({
    id: "disco-45",
    slug: "nach-a-traves-de-mi",
    title: "A Través De Mí",
    artist_names: ["Nach"],
    role: "Composer / Lyricist / Producer / Arranger / Piano",
    cover_url: "/discografia/nach-a-traves-de-mi.jpg",
    featured: false,
    sort_order: 45,
  }),
  album({
    id: "disco-46",
    slug: "dvicio-valeria",
    title: "Valeria",
    artist_names: ["DVICIO"],
    role: "Producer / Bass / Guitar / Programmer",
    cover_url: "/discografia/dvicio-valeria.jpg",
    spotify_url: "https://open.spotify.com/track/03CMxAJdSDN7qc4zR6Hja0",
    apple_music_url: "https://music.apple.com/es/album/valeria-single/1453219583",
    featured: false,
    sort_order: 46,
  }),
  album({
    id: "disco-47",
    slug: "david-bisbal-me-siento-vivo",
    title: "Me Siento Vivo",
    artist_names: ["David Bisbal"],
    role: "Producer",
    cover_url: "/discografia/david-bisbal-me-siento-vivo.jpg",
    spotify_url: "https://open.spotify.com/album/6ApKdCJZ8OeDoBDLHhvFkD",
    apple_music_url: "https://music.apple.com/us/album/me-siento-vivo/1704824116",
    featured: false,
    sort_order: 47,
  }),
  album({
    id: "disco-48",
    slug: "marquitos-un-buen-trabajo-p-ta",
    title: "Un Buen Trabajo, P*TA",
    artist_names: ["Marquitos"],
    role: "Producer",
    cover_url: "/discografia/marquitos-un-buen-trabajo-p-ta.jpg",
    featured: false,
    sort_order: 48,
  }),
  album({
    id: "disco-49",
    slug: "miss-caffeina-cuando-acabe-el-verano",
    title: "Cuando Acabe El Verano",
    artist_names: ["Miss Caffeina"],
    role: "Producer",
    cover_url: "/discografia/miss-caffeina-cuando-acabe-el-verano.jpg",
    spotify_url: "https://open.spotify.com/track/6y4MFrp5vwd4uJAI9e3UQ7",
    apple_music_url: "https://music.apple.com/mx/song/cuando-acabe-el-verano/1750548688",
    featured: false,
    sort_order: 49,
  }),
  album({
    id: "disco-50",
    slug: "alex-ubago-canciones-impuntuales",
    title: "Canciones Impuntuales",
    artist_names: ["Álex Ubago"],
    role: "Producer",
    cover_url: "/discografia/alex-ubago-canciones-impuntuales.jpg",
    spotify_url: "https://open.spotify.com/album/45j8ViyScyWIbfjlNwB1T7",
    apple_music_url: "https://music.apple.com/us/album/canciones-impuntuales/1219365225",
    featured: false,
    sort_order: 50,
  }),
  album({
    id: "disco-51",
    slug: "antonio-jose-el-pacto",
    title: "El Pacto",
    artist_names: ["Antonio José"],
    role: "Producer",
    cover_url: "/discografia/antonio-jose-el-pacto.jpg",
    spotify_url: "https://open.spotify.com/album/5Dt2lnQ9Q7sBV6AZzky5SY",
    apple_music_url: "https://music.apple.com/us/album/el-pacto/1695113754",
    featured: false,
    sort_order: 51,
  }),
  album({
    id: "disco-52",
    slug: "dvicio-el-laberinto",
    title: "El Laberinto",
    artist_names: ["DVICIO"],
    role: "Producer",
    cover_url: "/discografia/dvicio-el-laberinto.jpg",
    spotify_url: "https://open.spotify.com/album/3253tBHUBpqumSU2xnzo3o",
    apple_music_url: "https://music.apple.com/us/album/el-laberinto/1613197380",
    featured: false,
    sort_order: 52,
  }),
  album({
    id: "disco-53",
    slug: "david-bustamante-el-dia-que-te-vayas",
    title: "El Día Que Te Vayas",
    artist_names: ["David Bustamante"],
    role: "Producer / Arranger / Guitar / Keyboard / Programmer",
    cover_url: "/discografia/david-bustamante-el-dia-que-te-vayas.jpg",
    spotify_url: "https://open.spotify.com/track/6DceTo96v3HxMjSx2BFVKO",
    apple_music_url: "https://music.apple.com/ca/song/el-d%C3%ADa-que-te-vayas/1735713972",
    featured: false,
    sort_order: 53,
  }),
  album({
    id: "disco-54",
    slug: "antonio-jose-como-dejar-ir",
    title: "Cómo Dejar Ir",
    artist_names: ["Antonio José"],
    role: "Composer / Lyricist / Producer / Guitar / Programmer / Piano",
    cover_url: "/discografia/antonio-jose-como-dejar-ir.jpg",
    featured: false,
    sort_order: 54,
  }),
  album({
    id: "disco-55",
    slug: "julia-medina-companera-de-viaje",
    title: "Compañera De Viaje",
    artist_names: ["Julia Medina"],
    role: "Producer",
    cover_url: "/discografia/julia-medina-companera-de-viaje.jpg",
    spotify_url: "https://open.spotify.com/album/3nMbToTA9OvoK3Bii1mcMc",
    apple_music_url: "https://music.apple.com/us/album/compa%C3%B1era-de-viaje-ep/1737429712",
    featured: false,
    sort_order: 55,
  }),
  album({
    id: "disco-56",
    slug: "amaia-alfred-garcia-tu-cancion",
    title: "Tu Canción",
    artist_names: ["Amaia", "Alfred García"],
    role: "Producer",
    cover_url: "/discografia/amaia-alfred-garcia-tu-cancion.jpg",
    spotify_url: "https://open.spotify.com/album/1R4JweFIZ4Svc5Fi0hl3qy",
    apple_music_url: "https://music.apple.com/es/album/tu-canci%C3%B3n-single/1355888789",
    featured: false,
    sort_order: 56,
  }),
  album({
    id: "disco-57",
    slug: "india-martinez-palmeras",
    title: "Palmeras",
    artist_names: ["India Martínez"],
    role: "Producer",
    cover_url: "/discografia/india-martinez-palmeras.jpg",
    spotify_url: "https://open.spotify.com/album/44T0wt9lD2FnxPg5d2qXJL",
    apple_music_url: "https://music.apple.com/us/album/palmeras/1480757820",
    featured: false,
    sort_order: 57,
  }),
  album({
    id: "disco-58",
    slug: "toteking-78",
    title: "78",
    artist_names: ["ToteKing"],
    role: "Producer",
    cover_url: "/discografia/toteking-78.jpg",
    spotify_url: "https://open.spotify.com/album/2zKgiuqzlKLByt957YVKsB",
    apple_music_url: "https://music.apple.com/us/album/78/1021224976",
    featured: false,
    sort_order: 58,
  }),
  album({
    id: "disco-59",
    slug: "raphael-6-0",
    title: "6.0",
    artist_names: ["Raphael"],
    role: "Producer",
    cover_url: "/discografia/raphael-6-0.jpg",
    spotify_url: "https://open.spotify.com/album/3Yd62b2ujFhnLLko4UgTrg",
    apple_music_url: "https://music.apple.com/es/album/6-0/1536764116",
    featured: false,
    sort_order: 59,
  }),
  album({
    id: "disco-60",
    slug: "marta-soto-dire",
    title: "DiRÉ",
    artist_names: ["Marta Soto"],
    role: "Producer",
    cover_url: "/discografia/marta-soto-dire.jpg",
    featured: false,
    sort_order: 60,
  }),
  album({
    id: "disco-61",
    slug: "alfred-garcia-los-espabilados",
    title: "Los Espabilados",
    artist_names: ["Alfred García"],
    role: "Guitar / World Instrument",
    cover_url: "/discografia/alfred-garcia-los-espabilados.jpg",
    spotify_url: "https://open.spotify.com/track/09GehafNZgAd0vU7vTzqPg",
    apple_music_url: "https://music.apple.com/gb/music-video/los-espabilados-canci%C3%B3n-original-de-la-serie-los/1548030735",
    featured: false,
    sort_order: 61,
  }),
  album({
    id: "disco-62",
    slug: "manuel-carrasco-tributo-a-sabina",
    title: "Tributo a Sabina (La Canción Más Hermosa Del Mundo)",
    artist_names: ["Manuel Carrasco"],
    role: "Producer",
    cover_url: "/discografia/manuel-carrasco-tributo-a-sabina.jpg",
    spotify_url: "https://open.spotify.com/intl-es/track/2OgSwy6TigJbZD14tAoeRK",
    apple_music_url: "https://music.apple.com/es/album/la-canci%C3%B3n-m%C3%A1s-hermosa-del-mundo-single/1542992932",
    featured: false,
    sort_order: 62,
  }),
  album({
    id: "disco-63",
    slug: "ketama-loko-de-amor",
    title: "Loko De Amor",
    artist_names: ["Ketama"],
    role: "Producer",
    cover_url: "/discografia/ketama-loko-de-amor.jpg",
    spotify_url: "https://open.spotify.com/album/5zqDJ5G4ant6yyS2lhpZS0",
    apple_music_url: "https://music.apple.com/es/album/loko-de-amor-single/1444602955",
    featured: false,
    sort_order: 63,
  }),
  album({
    id: "disco-64",
    slug: "elle-what-night-hides",
    title: "What Night Hides",
    artist_names: ["ELE"],
    role: "Producer",
    cover_url: "/discografia/elle-what-night-hides.jpg",
    spotify_url: "https://open.spotify.com/album/7ILumFDUc2ZCh2ZILUyfeo",
    featured: false,
    sort_order: 64,
  }),
  album({
    id: "disco-65",
    slug: "paty-cantu-333-deluxe",
    title: "#333 Deluxe",
    artist_names: ["Paty Cantú"],
    role: "Producer",
    cover_url: "/discografia/paty-cantu-333-deluxe.jpg",
    spotify_url: "https://open.spotify.com/album/7EM9WhSsBvdEElzcmxOnp4",
    apple_music_url: "https://music.apple.com/gb/album/333-edici%C3%B3n-deluxe/1438768609",
    featured: false,
    sort_order: 65,
  }),
  album({
    id: "disco-66",
    slug: "carmen-paris-incubando",
    title: "inCubando",
    artist_names: ["Carmen Paris"],
    role: "Producer",
    cover_url: "/discografia/carmen-paris-incubando.jpg",
    spotify_url: "https://open.spotify.com/intl-es/album/0hvlE8yHGjFGYwaajznxV9",
    apple_music_url: "https://music.apple.com/us/album/incubando/279684759",
    featured: false,
    sort_order: 66,
  }),
  album({
    id: "disco-67",
    slug: "julia-medina-punto-de-partida",
    title: "Punto De Partida",
    artist_names: ["Julia Medina"],
    role: "Producer",
    cover_url: "/discografia/julia-medina-punto-de-partida.jpg",
    spotify_url: "https://open.spotify.com/track/3k8WMwD9HhvYXzbsoDHpTH",
    featured: false,
    sort_order: 67,
  }),
  album({
    id: "disco-68",
    slug: "fabula-crisalida",
    title: "Crisálida",
    artist_names: ["Fábula"],
    role: "Producer",
    cover_url: "/discografia/fabula-crisalida.jpg",
    apple_music_url: "https://music.apple.com/co/album/cris%C3%A1lida/218404964",
    featured: false,
    sort_order: 68,
  }),
];
