import { Album } from "./types";

/**
 * Discografía completa recuperada de la web anterior (pablocebrian.es,
 * Wix) mientras el cliente confirma fechas y sellos. Las portadas son las
 * originales del sitio. Una vez configurado Supabase, estos datos dejan de
 * usarse: se sustituyen por lo que el propio Pablo cargue desde
 * /admin/discos.
 */
function album(partial: {
  id: string;
  slug: string;
  title: string;
  artist_names: string[];
  role: string;
  cover_url: string;
  featured: boolean;
  sort_order: number;
}): Album {
  return {
    release_year: null,
    label: null,
    spotify_url: null,
    apple_music_url: null,
    youtube_url: null,
    published: true,
    ...partial,
  };
}

export const PLACEHOLDER_ALBUMS: Album[] = [
  album({
    id: "disco-1",
    slug: "manuel-carrasco-la-cruz-del-mapa",
    title: "La Cruz Del Mapa",
    artist_names: ["Manuel Carrasco"],
    role: "Composer / Lyricist / Producer / Arranger / Guitar / Programmer / Piano / Vocals",
    cover_url: "/discografia/manuel-carrasco-la-cruz-del-mapa.jpg",
    featured: true,
    sort_order: 1,
  }),
  album({
    id: "disco-2",
    slug: "siloe-santa-trinidad",
    title: "Santa Trinidad",
    artist_names: ["Siloé"],
    role: "Composer / Lyricist / Arranger / Producer",
    cover_url: "/discografia/siloe-santa-trinidad.jpg",
    featured: true,
    sort_order: 2,
  }),
  album({
    id: "disco-3",
    slug: "pedro-guerra-parceiros-vol-2",
    title: "Parceiros, Vol. 2",
    artist_names: ["Pedro Guerra"],
    role: "Producer / Arranger / Guitar / Bass / Programmer",
    cover_url: "/discografia/pedro-guerra-parceiros-vol-2.jpg",
    featured: true,
    sort_order: 3,
  }),
  album({
    id: "disco-4",
    slug: "luz-casal-me-voy-a-permitir",
    title: "Me Voy A Permitir",
    artist_names: ["Luz Casal"],
    role: "Composer",
    cover_url: "/discografia/luz-casal-me-voy-a-permitir.jpg",
    featured: true,
    sort_order: 4,
  }),
  album({
    id: "disco-5",
    slug: "residente-rap-bruto",
    title: "Rap Bruto",
    artist_names: ["Residente", "Nach"],
    role: "Composer / Lyricist / Producer / Arranger / Programmer",
    cover_url: "/discografia/residente-rap-bruto.jpg",
    featured: true,
    sort_order: 5,
  }),
  album({
    id: "disco-6",
    slug: "carlos-rivera-para-ti",
    title: "Para Ti",
    artist_names: ["Carlos Rivera"],
    role: "Lyricist / Composer / Producer / Bass",
    cover_url: "/discografia/carlos-rivera-para-ti.jpg",
    featured: true,
    sort_order: 6,
  }),
  album({
    id: "disco-7",
    slug: "vivafe-alzo-la-mirada",
    title: "Alzo la Mirada",
    artist_names: ["VIVAFE", "Gran Coro de Voces Católicas"],
    role: "Composer / Lyricist / Producer / Arranger / Guitar / Bass / Programmer",
    cover_url: "/discografia/vivafe-alzo-la-mirada.jpg",
    featured: true,
    sort_order: 7,
  }),
  album({
    id: "disco-8",
    slug: "manuel-carrasco-bailar-el-viento",
    title: "Bailar El Viento",
    artist_names: ["Manuel Carrasco"],
    role: "Producer / Arranger / Bass / Guitar / Programmer",
    cover_url: "/discografia/manuel-carrasco-bailar-el-viento.jpg",
    featured: true,
    sort_order: 8,
  }),
  album({
    id: "disco-9",
    slug: "conchita-la-orilla",
    title: "La Orilla",
    artist_names: ["Conchita"],
    role: "Producer / Programmer / Guitar / Bass / Piano",
    cover_url: "/discografia/conchita-la-orilla.jpg",
    featured: true,
    sort_order: 9,
  }),
  album({
    id: "disco-10",
    slug: "aitana-spoiler",
    title: "Spoiler",
    artist_names: ["Aitana"],
    role: "Producer",
    cover_url: "/discografia/aitana-spoiler.jpg",
    featured: true,
    sort_order: 10,
  }),
  album({
    id: "disco-11",
    slug: "antonito-molina-dejemos-huellas-bonitas",
    title: "Dejemos Huellas Bonitas",
    artist_names: ["Antoñito Molina"],
    role: "Producer",
    cover_url: "/discografia/antonito-molina-dejemos-huellas-bonitas.jpg",
    featured: true,
    sort_order: 11,
  }),
  album({
    id: "disco-12",
    slug: "david-bisbal-en-tus-planes",
    title: "En Tus Planes",
    artist_names: ["David Bisbal"],
    role: "Co-Producer",
    cover_url: "/discografia/david-bisbal-en-tus-planes.jpg",
    featured: true,
    sort_order: 12,
  }),
  album({
    id: "disco-13",
    slug: "tuyo-tu-el-unico-rey-una-voz",
    title: "(Tú) El Único Rey - Una Voz",
    artist_names: ["Tuyo", "Hakuna Group Music", "Aisha Ruah"],
    role: "Producer / Piano / Programmer / Bass / Guitar / Keyboard",
    cover_url: "/discografia/tuyo-tu-el-unico-rey-una-voz.jpg",
    featured: true,
    sort_order: 13,
  }),
  album({
    id: "disco-14",
    slug: "ketama-de-aki-a-ketama",
    title: "De Akí A Ketama",
    artist_names: ["Ketama"],
    role: "Producer / Programmer",
    cover_url: "/discografia/ketama-de-aki-a-ketama.jpg",
    featured: true,
    sort_order: 14,
  }),
  album({
    id: "disco-15",
    slug: "gonzalo-hermida-bandera-libertad",
    title: "Bandera Libertad",
    artist_names: ["Gonzalo Hermida", "Andrés Koi"],
    role: "Composer / Lyricist / Producer",
    cover_url: "/discografia/gonzalo-hermida-bandera-libertad.jpg",
    featured: true,
    sort_order: 15,
  }),
  album({
    id: "disco-16",
    slug: "resistire-2020-resistire",
    title: "Resistiré",
    artist_names: ["Resistiré 2020"],
    role: "Producer / Guitar",
    cover_url: "/discografia/resistire-2020-resistire.jpg",
    featured: true,
    sort_order: 16,
  }),
  album({
    id: "disco-17",
    slug: "viva-suecia-alegria-de-vivir",
    title: "Alegría De Vivir",
    artist_names: ["Viva Suecia"],
    role: "Producer / Guitar / Vocals",
    cover_url: "/discografia/viva-suecia-alegria-de-vivir.jpg",
    featured: true,
    sort_order: 17,
  }),
  album({
    id: "disco-18",
    slug: "david-bisbal-todo-es-posible-en-navidad",
    title: "Todo Es Posible En Navidad",
    artist_names: ["David Bisbal"],
    role: "Composer / Lyricist",
    cover_url: "/discografia/david-bisbal-todo-es-posible-en-navidad.jpg",
    featured: true,
    sort_order: 18,
  }),
  album({
    id: "disco-19",
    slug: "luz-casal-que-has-hecho-conmigo",
    title: "¿Qué Has Hecho Conmigo?",
    artist_names: ["Luz Casal"],
    role: "Composer / Guitar",
    cover_url: "/discografia/luz-casal-que-has-hecho-conmigo.jpg",
    featured: true,
    sort_order: 19,
  }),
  album({
    id: "disco-20",
    slug: "pedro-guerra-parceiros-vol-3",
    title: "Parceiros, Vol. 3",
    artist_names: ["Pedro Guerra"],
    role: "Producer / Guitar / Bass / Programmer",
    cover_url: "/discografia/pedro-guerra-parceiros-vol-3.jpg",
    featured: true,
    sort_order: 20,
  }),
  album({
    id: "disco-21",
    slug: "taburete-matadero-5",
    title: "Matadero 5",
    artist_names: ["Taburete"],
    role: "Producer / Arranger / Guitar / Bass / Programmer",
    cover_url: "/discografia/taburete-matadero-5.jpg",
    featured: true,
    sort_order: 21,
  }),
  album({
    id: "disco-22",
    slug: "bunbury-cuentas-pendientes",
    title: "Cuentas Pendientes",
    artist_names: ["Bunbury"],
    role: "Arranger",
    cover_url: "/discografia/bunbury-cuentas-pendientes.jpg",
    featured: true,
    sort_order: 22,
  }),
  album({
    id: "disco-23",
    slug: "sole-gimenez-ser-humano",
    title: "Ser Humano",
    artist_names: ["Sole Giménez"],
    role: "Composer / Producer / Lyricist / Bass / Guitar / Keyboard",
    cover_url: "/discografia/sole-gimenez-ser-humano.jpg",
    featured: true,
    sort_order: 23,
  }),
  album({
    id: "disco-24",
    slug: "beret-si-te-vuelvo-a-llamar",
    title: "Si Te Vuelvo A Llamar",
    artist_names: ["Beret"],
    role: "Producer / Guitar / Keyboard / Programmer",
    cover_url: "/discografia/beret-si-te-vuelvo-a-llamar.jpg",
    featured: true,
    sort_order: 24,
  }),
  album({
    id: "disco-25",
    slug: "hakuna-group-music-tu",
    title: "Tú",
    artist_names: ["Hakuna Group Music", "Aisha Ruah", "Clara H.", "Ecos Música"],
    role: "Composer / Producer / Piano / Programmer / Guitar / Keyboard / Bass",
    cover_url: "/discografia/hakuna-group-music-tu.jpg",
    featured: true,
    sort_order: 25,
  }),
  album({
    id: "disco-26",
    slug: "julia-debis-la-memoria",
    title: "La Memoria",
    artist_names: ["Julia Debis"],
    role: "Composer / Lyricist",
    cover_url: "/discografia/julia-debis-la-memoria.jpg",
    featured: false,
    sort_order: 26,
  }),
  album({
    id: "disco-27",
    slug: "vivafe-i-ll-lift-up-my-eyes",
    title: "I'll Lift Up My Eyes",
    artist_names: ["VIVAFE", "Matt Maher", "Sarah Kroger"],
    role: "Composer / Lyricist / Producer",
    cover_url: "/discografia/vivafe-i-ll-lift-up-my-eyes.jpg",
    featured: false,
    sort_order: 27,
  }),
  album({
    id: "disco-28",
    slug: "los-enanitos-verdes-creo",
    title: "Creo",
    artist_names: ["Los Enanitos Verdes", "David Summers"],
    role: "Producer",
    cover_url: "/discografia/los-enanitos-verdes-creo.jpg",
    featured: false,
    sort_order: 28,
  }),
  album({
    id: "disco-29",
    slug: "tuyo-aleluya",
    title: "Aleluya",
    artist_names: ["Tuyo"],
    role: "Producer",
    cover_url: "/discografia/tuyo-aleluya.jpg",
    featured: false,
    sort_order: 29,
  }),
  album({
    id: "disco-30",
    slug: "beret-hablo-de-ti",
    title: "Hablo de Ti",
    artist_names: ["Beret"],
    role: "Producer / Keyboard / Guitar / Instrumentation",
    cover_url: "/discografia/beret-hablo-de-ti.jpg",
    featured: false,
    sort_order: 30,
  }),
  album({
    id: "disco-31",
    slug: "andres-koi-sol-de-invierno",
    title: "Sol De Invierno",
    artist_names: ["Andrés Koi", "Taburete"],
    role: "Producer / Programmer / Guitar / Bass",
    cover_url: "/discografia/andres-koi-sol-de-invierno.jpg",
    featured: false,
    sort_order: 31,
  }),
  album({
    id: "disco-32",
    slug: "naike-ponce-que-bonito-es-querer",
    title: "Qué Bonito Es Querer",
    artist_names: ["Naike Ponce"],
    role: "Composer",
    cover_url: "/discografia/naike-ponce-que-bonito-es-querer.jpg",
    featured: false,
    sort_order: 32,
  }),
  album({
    id: "disco-33",
    slug: "antonio-jose-luz",
    title: "Luz",
    artist_names: ["Antonio José"],
    role: "Producer / Composer / Lyricist",
    cover_url: "/discografia/antonio-jose-luz.jpg",
    featured: false,
    sort_order: 33,
  }),
  album({
    id: "disco-34",
    slug: "hermanos-martinez-contacto-de-emergencia",
    title: "Contacto De Emergencia",
    artist_names: ["Hermanos Martínez", "Mau y Ricky"],
    role: "Producer",
    cover_url: "/discografia/hermanos-martinez-contacto-de-emergencia.jpg",
    featured: false,
    sort_order: 34,
  }),
  album({
    id: "disco-35",
    slug: "maria-leon-las-damas-y-el-vagabundo",
    title: "Las Damas y El Vagabundo",
    artist_names: ["María León", "Julia Medina"],
    role: "Composer",
    cover_url: "/discografia/maria-leon-las-damas-y-el-vagabundo.jpg",
    featured: false,
    sort_order: 35,
  }),
  album({
    id: "disco-36",
    slug: "luis-ramiro-cinecitta",
    title: "Cinecittà",
    artist_names: ["Luis Ramiro"],
    role: "Producer",
    cover_url: "/discografia/luis-ramiro-cinecitta.jpg",
    featured: false,
    sort_order: 36,
  }),
  album({
    id: "disco-37",
    slug: "gonzalo-hermida-vivir-es-una-fiesta",
    title: "Vivir Es Una Fiesta",
    artist_names: ["Gonzalo Hermida"],
    role: "Producer",
    cover_url: "/discografia/gonzalo-hermida-vivir-es-una-fiesta.jpg",
    featured: false,
    sort_order: 37,
  }),
  album({
    id: "disco-38",
    slug: "hermanos-martinez-feliz-navidad",
    title: "Feliz Navidad",
    artist_names: ["Hermanos Martínez"],
    role: "Producer",
    cover_url: "/discografia/hermanos-martinez-feliz-navidad.jpg",
    featured: false,
    sort_order: 38,
  }),
  album({
    id: "disco-39",
    slug: "miriam-rodriguez-hay-algo-en-mi-live-las-ventas",
    title: "Hay Algo En Mí (Live Las Ventas)",
    artist_names: ["Miriam Rodríguez"],
    role: "Composer / Lyricist",
    cover_url: "/discografia/miriam-rodriguez-hay-algo-en-mi-live-las-ventas.jpg",
    featured: false,
    sort_order: 39,
  }),
  album({
    id: "disco-40",
    slug: "beret-nadie-mas-te-la-cree",
    title: "Nadie Más Te La Cree",
    artist_names: ["Beret"],
    role: "Lyricist / Composer / Guitar / Producer / Arrangements / Piano / Vocals / Percussion / Programmer",
    cover_url: "/discografia/beret-nadie-mas-te-la-cree.png",
    featured: false,
    sort_order: 40,
  }),
  album({
    id: "disco-41",
    slug: "marquitos-bucle",
    title: "Bucle",
    artist_names: ["Marquitos"],
    role: "Producer / Guitar / Piano",
    cover_url: "/discografia/marquitos-bucle.jpg",
    featured: false,
    sort_order: 41,
  }),
  album({
    id: "disco-42",
    slug: "julia-medina-mi-templo",
    title: "Mi Templo",
    artist_names: ["Julia Medina"],
    role: "Producer / Piano",
    cover_url: "/discografia/julia-medina-mi-templo.jpg",
    featured: false,
    sort_order: 42,
  }),
  album({
    id: "disco-43",
    slug: "hermanos-martinez-me-voy-contigo",
    title: "Me Voy Contigo",
    artist_names: ["Hermanos Martínez"],
    role: "Producer",
    cover_url: "/discografia/hermanos-martinez-me-voy-contigo.jpg",
    featured: false,
    sort_order: 43,
  }),
  album({
    id: "disco-44",
    slug: "siloe-todos-los-besos-remix",
    title: "Todos Los Besos (Remix)",
    artist_names: ["Siloé", "DJ Nano"],
    role: "Lyricist / Composer / Producer / Arranger",
    cover_url: "/discografia/siloe-todos-los-besos-remix.jpg",
    featured: false,
    sort_order: 44,
  }),
  album({
    id: "disco-45",
    slug: "sole-gimenez-esa-vieja-melodia",
    title: "Esa Vieja Melodía",
    artist_names: ["Sole Giménez", "El Kanka"],
    role: "Producer",
    cover_url: "/discografia/sole-gimenez-esa-vieja-melodia.jpg",
    featured: false,
    sort_order: 45,
  }),
];
